name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "Está rodando com ubuntu runner"
          echo "Runner OS $RUNNER_OS"