name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows/04-using-actions/react-app
    steps:
      - name: Verificar Código
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Test
        run: npm run test
    # 0. Verificar o código do repositório
    # 1. Instalar deps da nossa aplicação em react
    # 2. Executar testes automatizados