name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rodar sempre que uma pull é acionada ou sincronizada e a branch é a principal"