name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rodar sempre que uma pull está closed"