name: 10 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "Print if step succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "Print if any step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "Always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "Print if the workflow is cancelled."